server:
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: true


spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: ksky8013
    password: azzxpfgmvffcstyv
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: testdbuser
    password: 1234

mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true






