spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: testdbuser
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
    show-sql: true

mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
    - classpath:mybatis/mapper/*.xml





